name: release

on:
  push:
    branches:
      - "*"
  pull_request:

env:
  COUNTRY: United States # [!] Do not change. This env is used to find fast mirror server. (Github Actions' workers are running in US.)
  REPO_DIR: /tmp/repo
  BUILD_DIR: /tmp/build
  CCACHE_DIR: /tmp/ccache
  GIT_REMOTE: https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
  GIT_BRANCH: gh-pages
  GIT_COMMIT_SHA: ${{ github.sha }}

jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm/v7
      - uses: actions/cache@v2
        with:
          key: cache
          path: |
            ${{ env.BUILD_DIR }}
            ${{ env.CCACHE_DIR }}
      - run: |
          ./tasks.sh initialize
      - run: |
          ./tasks.sh package
      - uses: actions/upload-artifact@v2
        with:
          name: artifact-packages
          path: ${{ env.BUILD_DIR }}
  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ${{ env.BUILD_DIR }}
      - run: |
          ./tasks.sh repository
      - run: |
          ./tasks.sh setup_git
      - run: |
          ./tasks.sh commit
      - run: |
          ./tasks.sh push
